server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:my-awesome-db
    username: username
    password: password
    initialization-mode: always
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2